# Generated by Django 4.0.3 on 2022-04-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semestre', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='groupes',
            field=models.ManyToManyField(null=True, to='semestre.groupe'),
        ),
    ]
