# Generated by Django 3.2.6 on 2022-04-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semestre', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('specialite', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('profile_pic', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='students',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='code_apogee',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='groupes',
            field=models.ManyToManyField(null=True, to='semestre.Groupe'),
        ),
        migrations.AddField(
            model_name='students',
            name='path_photos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='telephone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Professeur'), (3, 'Etudiant')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
        migrations.AlterField(
            model_name='students',
            name='cne',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
