# Generated by Django 3.0.7 on 2022-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='apoge_number',
        ),
        migrations.RemoveField(
            model_name='students',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='place',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='research',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='training_name',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='year',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Superuser',
        ),
    ]
