# Generated by Django 3.2.6 on 2022-04-28 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_chapitre_professeur'),
        ('module', '0004_auto_20220428_0443'),
        ('emploie', '0003_alter_planning_professeur'),
        ('users', '0002_auto_20220428_0443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='users.Permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professeur',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
