# Generated by Django 3.2.6 on 2022-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students_groupes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='address',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='specialite',
        ),
        migrations.AddField(
            model_name='professeur',
            name='speciality',
            field=models.CharField(default='informatique', max_length=45),
        ),
    ]
