# Generated by Django 4.0.4 on 2022-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students_groupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
