# Generated by Django 4.0.4 on 2022-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cne',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='code_apogee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
