# Generated by Django 3.2.6 on 2022-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220428_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='speciality',
            field=models.CharField(default='informatique', max_length=120),
        ),
    ]
