# Generated by Django 3.2.6 on 2022-04-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_professeur_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='speciality',
            field=models.TextField(),
        ),
    ]
