# Generated by Django 3.2.6 on 2022-04-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_professeur_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='speciality',
        ),
    ]
