# Generated by Django 4.0.4 on 2022-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_professeur_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='professeur',
            name='specialite',
            field=models.CharField(default='informatique', max_length=45),
        ),
        migrations.AddField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
