# Generated by Django 4.0.4 on 2022-05-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_students_cne_alter_students_code_apogee_and_more'),
        ('users', '0007_professeur_matricule_professeur_specialite_and_more'),
    ]

    operations = [
    ]
