# Generated by Django 4.0.4 on 2022-05-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20220518_2338'),
        ('users', '0008_merge_20220519_0057'),
    ]

    operations = [
    ]
