# Generated by Django 4.0.3 on 2022-05-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20220521_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='telephone',
        ),
    ]
