# Generated by Django 3.2.6 on 2022-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumeHoraire', models.IntegerField()),
                ('objectif', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant_Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsable', models.BooleanField()),
                ('annee_universitaire', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_module', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
