# Generated by Django 3.2.6 on 2022-04-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('module', '0001_initial'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semestre.semestre'),
        ),
        migrations.AddField(
            model_name='enseignant_responsable',
            name='element_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.elementmodule'),
        ),
        migrations.AddField(
            model_name='enseignant_responsable',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.module'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='perequis',
            field=models.ManyToManyField(related_name='perequises', to='module.ElementModule'),
        ),
    ]
