# Generated by Django 4.0.4 on 2022-05-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_professeur_matricule_professeur_specialite_and_more'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmodule',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_responsable', to='users.professeur'),
        ),
        migrations.AlterField(
            model_name='perequis',
            name='element_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_element_module', to='module.elementmodule'),
        ),
        migrations.AlterField(
            model_name='perequis',
            name='prerequis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_prerequis', to='module.elementmodule'),
        ),
    ]
