# Generated by Django 3.0.7 on 2022-04-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('module', '0002_auto_20220421_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant_responsable',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Teachers'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.Module'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='perequis',
            field=models.ManyToManyField(related_name='perequises', to='module.ElementModule'),
        ),
    ]
