# Generated by Django 3.2.6 on 2022-04-28 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perequis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='elementmodule',
            name='perequis',
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='libelle_element_module',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
