# Generated by Django 3.2.6 on 2022-04-28 04:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220428_0443'),
        ('semestre', '0001_initial'),
        ('module', '0003_auto_20220428_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementmodule',
            name='prof_id',
            field=models.ManyToManyField(to='users.Professeur'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='responsable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elementmodule_responsable', to='users.professeur'),
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.AlterField(
            model_name='elementmodule',
            name='objectif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enseignant_responsable',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.professeur'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='semestre.semestre'),
        ),
        migrations.AddField(
            model_name='perequis',
            name='element_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perequis_element_module', to='module.elementmodule'),
        ),
        migrations.AddField(
            model_name='perequis',
            name='prerequis_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perequis_prerequis', to='module.elementmodule'),
        ),
    ]
