<<<<<<< HEAD
# Generated by Django 3.0.7 on 2022-04-21 10:50
=======
# Generated by Django 4.0.3 on 2022-04-12 18:01
>>>>>>> ecaf05613685bad4c664a487587c9d81ef7f8e59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liblle', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=100, null=True)),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeSalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite', models.IntegerField(max_length=100)),
                ('libelle', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('planning', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.Planning')),
            ],
        ),
    ]
