# Generated by Django 3.2.6 on 2022-04-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('emploie', '0001_initial'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semestre.groupe'),
        ),
        migrations.AddField(
            model_name='planning',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.salle'),
        ),
    ]
