# Generated by Django 3.0.7 on 2022-04-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emploie', '0001_initial'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semestre.Groupe'),
        ),
    ]
