# Generated by Django 3.2.6 on 2022-05-04 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_students_groupes'),
        ('module', '0001_initial'),
        ('emploie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='element_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.elementmodule'),
        ),
        migrations.AddField(
            model_name='presence',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.students'),
        ),
        migrations.AddField(
            model_name='presence',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.seance'),
        ),
        migrations.AddField(
            model_name='salle',
            name='type_salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.typesalle'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='planning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.planning'),
        ),
        migrations.AlterField(
            model_name='typesalle',
            name='capacite',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
