# Generated by Django 4.0.3 on 2022-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0002_auto_20220504_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='liblle',
        ),
        migrations.AddField(
            model_name='planning',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
