# Generated by Django 3.0.7 on 2022-04-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emploie', '0002_planning_groupe'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Teachers'),
        ),
        migrations.AddField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.Salle'),
        ),
    ]
