# Generated by Django 4.0.3 on 2022-05-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0003_remove_planning_liblle_planning_date_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='planning',
            name='jour',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
