# Generated by Django 4.0.3 on 2022-05-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0004_remove_planning_date_debut_remove_planning_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
