# Generated by Django 4.0.3 on 2022-05-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0005_remove_seance_date_debut_remove_seance_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='planning',
        ),
    ]
