# Generated by Django 4.0.3 on 2022-05-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0006_remove_seance_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='planning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploie.planning'),
        ),
    ]
