# Generated by Django 4.0.3 on 2022-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0007_seance_planning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='heure_fin',
        ),
        migrations.AddField(
            model_name='planning',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
