# Generated by Django 4.0.4 on 2022-05-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0008_remove_seance_heure_debut_remove_seance_heure_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='libelle',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
