# Generated by Django 4.0.4 on 2022-05-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0009_planning_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
