# Generated by Django 4.0.3 on 2022-04-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=30)),
                ('logo', models.ImageField(default='default.jpg', upload_to='filiere_images')),
            ],
        ),
    ]
