# Generated by Django 4.0.3 on 2022-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='logo',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='filiere_images'),
        ),
    ]
