<<<<<<< HEAD
# Generated by Django 3.0.7 on 2022-04-21 10:50
=======
# Generated by Django 4.0.3 on 2022-04-12 18:01
>>>>>>> ecaf05613685bad4c664a487587c9d81ef7f8e59

from django.db import migrations, models
import django.db.models.deletion
import filiere.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('logo', models.ImageField(upload_to=filiere.models.upload_location_etablissement)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=30)),
<<<<<<< HEAD
                ('logo', models.ImageField(upload_to=filiere.models.upload_location)),
                ('etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiere.Etablissement')),
=======
                ('logo', models.ImageField(upload_to=filiere.models.upload_location_filiere)),
                ('etablissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiere.etablissement')),
>>>>>>> ecaf05613685bad4c664a487587c9d81ef7f8e59
            ],
        ),
    ]
