# Generated by Django 3.2.6 on 2022-04-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modele3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('chapitre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.chapitre')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.image')),
                ('modele3D', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.modele3d')),
            ],
        ),
        migrations.AddField(
            model_name='chapitre',
            name='Document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.document'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='ElementModule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.elementmodule'),
        ),
    ]
