# Generated by Django 4.0.4 on 2022-05-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_professeur_matricule_professeur_specialite_and_more'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibiliteModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modele3D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.modele3d')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professeur')),
            ],
        ),
    ]
