# Generated by Django 3.2.6 on 2022-04-14 10:53

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='Document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='chapitre',
            old_name='ElementModule',
            new_name='element_module',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(default='/static/img/cours/folder-files-and-folders-svgrepo-com.svg', upload_to=cours.models.upload_location),
        ),
    ]
