# Generated by Django 3.2.6 on 2022-04-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220428_0443'),
        ('cours', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professeur'),
        ),
    ]
