# Generated by Django 4.0.4 on 2022-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_professeur_matricule_professeur_specialite_and_more'),
        ('cours', '0002_visibilitemodele'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='visibilite',
            field=models.ManyToManyField(to='users.professeur'),
        ),
        migrations.DeleteModel(
            name='VisibiliteModele',
        ),
    ]
