# Generated by Django 3.2.6 on 2022-04-28 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20220428_0443'),
        ('cours', '0003_alter_chapitre_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='element_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.elementmodule'),
        ),
    ]
