# Generated by Django 3.2.6 on 2022-04-17 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_chapitre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='document',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapitre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cours.chapitre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modele3d',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modele3d',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traitement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cours.chapitre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traitement',
            name='modele3D',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.modele3d'),
        ),
    ]
