# Generated by Django 3.2.6 on 2022-04-28 05:47

import cours.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_auto_20220428_0443'),
        ('cours', '0004_alter_chapitre_element_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modele3d',
            old_name='path',
            new_name='path_modele3d',
        ),
        migrations.RenameField(
            model_name='traitement',
            old_name='titre',
            new_name='titre_traitement',
        ),
        migrations.RenameField(
            model_name='traitement',
            old_name='type',
            new_name='type_traitement',
        ),
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='label',
        ),
        migrations.AddField(
            model_name='image',
            name='is_qrcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='name_image',
            field=models.CharField(default='Sans Nom', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='path_image',
            field=models.FileField(default='NULL', upload_to=cours.models.model_image_location),
        ),
        migrations.AddField(
            model_name='modele3d',
            name='titre_modele3d',
            field=models.CharField(default='Sans Nom', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traitement',
            name='label_traitement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='element_module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.elementmodule'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='NULL', upload_to=cours.models.document_image_upload_location),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='image',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.image'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.FileField(max_length=255, upload_to=cours.models.file_upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modele3D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.modele3d')),
            ],
        ),
    ]
