# Generated by Django 3.2.6 on 2022-04-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_chapitre_enseignant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapitre',
            old_name='enseignant',
            new_name='professeur',
        ),
    ]
