# Generated by Django 3.2.6 on 2022-04-18 11:17

import cours.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_rename_enseignant_chapitre_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='image',
            field=models.ImageField(default='/img/cours/folder-files-and-folders-svgrepo-com.svg', upload_to=cours.models.upload_location),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='image',
            field=models.ForeignKey(default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.image'),
        ),
    ]
