# Generated by Django 3.2.6 on 2022-04-18 11:36

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_auto_20220418_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default='NULL', upload_to=cours.models.upload_location),
        ),
    ]
