# Generated by Django 3.2.6 on 2022-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0008_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='type',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
