# Generated by Django 3.2.6 on 2022-04-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_traitement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='sans nom', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modele3D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.modele3d')),
            ],
        ),
    ]
