# Generated by Django 3.2.6 on 2022-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_auto_20220422_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='Sans Nom', max_length=30),
        ),
    ]
