# Generated by Django 3.2.6 on 2022-04-22 14:35

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_alter_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='titre',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='/', upload_to=cours.models.file_upload_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modele3d',
            name='titre',
            field=models.CharField(default='model', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='NULL', upload_to=cours.models.document_image_upload_location),
        ),
        migrations.AlterField(
            model_name='modele3d',
            name='path',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>.2022-04-22-14-34-48', max_length=100),
        ),
    ]
