# Generated by Django 3.2.6 on 2022-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0012_auto_20220422_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modele3d',
            name='path',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>.2022-04-22-14-37-53', max_length=100),
        ),
    ]
