# Generated by Django 3.2.6 on 2022-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_auto_20220422_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='titre',
            field=models.CharField(default='Sans Titre', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modele3d',
            name='path',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>.2022-04-22-15-01-37', max_length=100),
        ),
    ]
