# Generated by Django 3.2.6 on 2022-04-23 12:05

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_auto_20220422_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FileField(upload_to=cours.models.model_image_location),
        ),
        migrations.AlterField(
            model_name='modele3d',
            name='path',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>-2022-04-23-12-05-52', max_length=100),
        ),
    ]
