# Generated by Django 3.2.6 on 2022-04-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0017_auto_20220423_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modele3d',
            name='path',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>-2022-04-23-23-22-27', max_length=100),
        ),
    ]
