# Generated by Django 3.2.6 on 2022-04-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0018_alter_modele3d_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_qrcode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modele3d',
            name='path',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>-2022-04-26-04-46-44', max_length=100),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='label',
            field=models.CharField(default='NULL', max_length=100, null=True),
        ),
    ]
