# Generated by Django 3.2.6 on 2022-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0019_auto_20220426_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='path_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='name_image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='path_image',
        ),
        migrations.RenameField(
            model_name='modele3d',
            old_name='titre',
            new_name='titre_modele3d',
        ),
        migrations.RenameField(
            model_name='traitement',
            old_name='label',
            new_name='label_traitement',
        ),
        migrations.RenameField(
            model_name='traitement',
            old_name='titre',
            new_name='titre_traitement',
        ),
        migrations.RenameField(
            model_name='traitement',
            old_name='type',
            new_name='type_traitement',
        ),
        migrations.RemoveField(
            model_name='modele3d',
            name='path',
        ),
        migrations.AddField(
            model_name='modele3d',
            name='path_modele3d',
            field=models.CharField(default='img/cours/modeles_3d/<django.db.models.fields.CharField>-2022-04-26-05-18-00', max_length=100),
        ),
    ]
