# Generated by Django 3.2.6 on 2022-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0020_auto_20220426_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modele3d',
            name='path_modele3d',
            field=models.CharField(max_length=100),
        ),
    ]
