# Generated by Django 3.2.6 on 2022-04-26 07:47

import cours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0021_alter_modele3d_path_modele3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path_file',
            field=models.FileField(max_length=255, upload_to=cours.models.file_upload_location),
        ),
    ]
