# Generated by Django 3.2.6 on 2022-04-27 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0022_alter_file_path_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.image'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='label_traitement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
