# Generated by Django 3.2.6 on 2022-04-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0023_auto_20220427_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitement',
            name='image',
            field=models.ForeignKey(blank=True, default='NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.image'),
        ),
    ]
