# Generated by Django 3.2.6 on 2022-04-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semestre', '0002_niveau_filliere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niveau',
            old_name='filliere',
            new_name='filiere',
        ),
    ]
